### ISSUE TITLE
joining the effort on https://gitlab.inria.fr/sed-rennes/sharelatex/python-sharelatex/

### ISSUE THREAD

**Issue by msimonin** [pstoeckle/ShareLaTeX-Versioning#1]
Hi there,

I just discovered this project when listing projects on pypi: https://pypi.org/search/?q=sharelatex
I just wanted to point out that we're maintaining a similar project at Inria: https://gitlab.inria.fr/sed-rennes/sharelatex/python-sharelatex
We've got a [python API](https://gitlab.inria.fr/sed-rennes/sharelatex/python-sharelatex/-/blob/03f14cfec4b9f9639ac903ed1c8901f5bf89a6a2/sharelatex/__init__.py#L452) for classical operations on projects and  [a command line interface](https://gitlab.inria.fr/sed-rennes/sharelatex/python-sharelatex/-/blob/03f14cfec4b9f9639ac903ed1c8901f5bf89a6a2/sharelatex/cli.py) that integrates with git.

The tool is designed to allow people to work offline (by pulling a sharelatex projects and pushing it back later) and supports  different and almost pluggable authentication methods (e.g see [here](https://gitlab.inria.fr/sed-rennes/sharelatex/python-sharelatex/-/blob/03f14cfec4b9f9639ac903ed1c8901f5bf89a6a2/sharelatex/__init__.py#L221-434) )

So the question would be, how about joining our effort ?

**Comment by pstoeckle** [comment]
> I just wanted to point out that we're maintaining a similar project at Inria: https://gitlab.inria.fr/sed-rennes/sharelatex/python-sharelatex

Salut ! I was not aware of your project, but it looks way more sophisticated compared to this one here! 

> So the question would be, how about joining our effort ?

Sounds good, but I cannot create an account on your GitLab on my own ...

**Comment by pstoeckle** [comment]
Could you send me an invitation to your GitLab instance?

**Comment by msimonin** [comment]
Hi @pstoeckle ,

I've just created an external account in our instance.  You should have received an email at your posteo.de address.
Let me know how it goes.

**Comment by pstoeckle** [comment]
The invitation worked and I created an account. Could you add me to the project as developer? Otherwise, I cannot create branches or merge requests.
